language: ruby
cache: bundler
sudo: false
bundler_args: --without debugger
rvm:
  - 2.4.1
  - 2.5.0
script:
  - bundle exec rake test

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
